### ISSUE TITLE
1.42 doesnt work right.  Use 1.41 somehow...

### ISSUE THREAD

**Issue by carterson2** [carterson2/speed-limit-grabber-chrome-extension#2]
I may be the culpret? Perhaps Alirio can figure it out.

I made the last change. I change manifest.*  1.41 to 1.42.
But perhaps that broke something, but I bet it was broke before that.

Linus had put in semicolns, and I think he didn't start with Alirios auto-button files.

Symptom: Click on icon says "not valid street page".
Alirio had fixed that to automagically redirect to hey_tryhere.php

**Comment by arevalirio** [comment]
@carterson2 It seems that @Maphead committed an old version of the popup.js file (it's pretty much the same file I extracted from the speed3.zip deleted file).

If you agree I will commit again the new popup.js file (or just reverse it to the previous version in the github repository).

**Comment by carterson2** [comment]
yea, please do.  I can barely understand github.link
<https://xkcd.com/1597/> so I clicked on the BUG button...
Maphead is Linus....He was a rev behind. No biggie.

Thanks!

**Comment by arevalirio** [comment]
It's done. Please update your local copies before making any changes to the project. Thank you.

**Comment by carterson2** [comment]
i put it out as 1.42. Seems to work aok. Thanks Alirio and Linus!

Interesting what comes up in google search.... ;-)
https://malwaretips.com/blogs/remove-speed-limit-grabber-chrome-extension/

Aside:
To my browser, I added a separate bookmark to fetch tryhere.php whenever I
have a free minute... (see picture below)

[image: Inline image 1]
